web/router.ex
defmodule Iptrack.Router do
  use Iptrack.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Iptrack.Auth, repo: Iptrack.Repo    
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Iptrack do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController
    resources "/sessions", SessionController, only: [:new, :create, :delete]
  end

  scope "/manage", Iptrack do
    pipe_through [:browser, :authenticate_user] # Use the default browser stack

    resources "/portfolios", PortfolioController
  end

  # Other scopes may use custom stacks.
  # scope "/api", Iptrack do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule Iptrack.LayoutView do
  use Iptrack.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Iptrack!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container" role="main">
      <div class="header">
        <ol class="breadcrumb text-right">
          <%= if @current_user do %>
            <li><%= @current_user.username %></li>
          <!-- Algo no funciona al generar el código html correspondiente a un link con el método DELETE, por lo que opto por transformarlo en un GET cambiando la ruta en el router.ex para la función delete del Session Controller
            <li><%= link "Log out", to: session_path(@conn, :delete, @current_user), method: :delete %></li>
          -->
            <li><%= button "Log out", to: session_path(@conn, :delete, @current_user), method: :delete %></li>
          <% else %>
            <li><%= link "Register", to: user_path(@conn, :new) %></li>
            <li><%= link "Log in", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
        <span class="logo"></span>
      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body></html>